name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast --verbose
  coverage:
    name: Coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        toolchain: [nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast --verbose
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - uses: actions-rs/grcov@v0.1
        id: grcov
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1
        id: badge
        with:
          label: 'Coverage'
          status: ${{ steps.grcov.outputs.report }}
          path: ./badges/test-coverage.svg
          color: ${{
                   steps.coverage.outputs.coverage > 90 && 'green'              ||
                   steps.coverage.outputs.coverage > 80 && 'yellow,green'       ||
                   steps.coverage.outputs.coverage > 70 && 'yellow'             ||
                   steps.coverage.outputs.coverage > 60 && 'orange,yellow'      ||
                   steps.coverage.outputs.coverage > 50 && 'orange'             ||
                   steps.coverage.outputs.coverage > 40 && 'red,orange'         ||
                   steps.coverage.outputs.coverage > 30 && 'red,red,orange'     ||
                   steps.coverage.outputs.coverage > 20 && 'red,red,red,orange' ||
                   'red' }}
