name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Update tool chain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build project
        run: cargo build --verbose
      - name: Test project
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: |
            -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code
            -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests -Cinstrument-coverage
          RUSTDOCFLAGS: |
            -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code
            -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests -Cinstrument-coverage'
        run: cargo test --all-features --no-fail-fast --verbose
      - name: Gather coverage data
        id: coverage
        uses: actions-rs/grcov@v0.1