name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        toolchain: [stable, beta, nightly]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Update tool chain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
#      - name: Build project
#        run: cargo build --verbose
      - name: Test project
        run: cargo test --all-features --no-fail-fast --verbose
