name: Publish
on:
  push:
    tags:
      - [0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - name: Update tool chain
        run: |
          rustup update stable
          rustup default stable
      - name: Test project
        run: cargo test
      - name: Publish
        run: cargo publish --token ${{ secrets.CRATES_IO }}
