name: Test

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Test latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        toolchain: [stable, beta, nightly]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Update tool chain
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          rustup component add llvm-tools-preview --toolchain ${{ matrix.toolchain }}
      - name: Install coverage tool
        run:  cargo +stable install cargo-llvm-cov --locked
      - name: Test project and generate coverage report
        run: cargo llvm-cov --summary-only --lcov --output-path lcov.info
      - name: Publish coverage summary to job summary
        uses: livewing/lcov-job-summary@v1.1.0
        with:
          lcov: lcov.info